dist: trusty
language: cpp
compiler: gcc
sudo: true

branches:
  only:
   - develop

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-7
      - g++-7
      - mpich
      - libmpich-dev
      - clang

before_install:
  - export DEVROOT=/home/travis/build
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - pwd
  - export NP=`grep -c ^processor /proc/cpuinfo`
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --config gcc
  - cd ${DEVROOT}
  - wget https://cmake.org/files/v3.12/cmake-3.12.1.tar.gz
  - tar xzf cmake-3.12.1.tar.gz
  - cd ${DEVROOT}/cmake-3.12.1
  - ./bootstrap
  - make -j ${NP} && sudo make install
  - which cmake
  - cmake --version
  - export PATH=/usr/local/bin:${PATH}

script:
  - cd ${DEVROOT}/SCOREC/core
  - mkdir -p ${DEVROOT}/SCOREC/core/build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_INSTALL_PREFIX=${DEVROOT}/install/core -DIS_TESTING=ON -DBUILD_EXES=ON -DCMAKE_BUILD_TYPE=Release -DMESHES=${DEVROOT}/SCOREC/core/pumi-meshes
  - make -j ${NP}
  - ctest --output-on-failure
  - cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_INSTALL_PREFIX=${DEVROOT}/install/core -DIS_TESTING=ON -DBUILD_EXES=ON -DCMAKE_BUILD_TYPE=Debug -DMESHES=${DEVROOT}/SCOREC/core/pumi-meshes
  - make -j ${NP}
  - ctest --output-on-failure

