cmake -S . -B /lore/mccalf/build \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpicxx \
    -DSCOREC_CXX_WARNINGS=on \
    -DIS_TESTING=on \
    -DBUILD_EXES=on \
    -DMESHES=/users/mccalf/pcu-update/pumi-meshes \
    -DENABLE_ZOLTAN=on \
    -DSIM_MPI=mpich4.1.1 \
    -DSIM_PARASOLID=on \
    -DSIM_ACIS=on \
    -DENABLE_SIMMETRIX=on \
    -DSKIP_SIMMETRIX_VERSION_CHECK=ON \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DCMAKE_INSTALL_PREFIX=/lore/mccalf/coreInstall/
