PREFIX=/lore/seol/mpich3-gcc4.9.2-install
SIM_VER=12.0-181124
SIM_ARCHOS=x64_rhel7_gcc48
PARMETIS_INSTALL_DIR=/usr/local/parmetis/4.0.3/mpich3.1.2 
ZOLTAN_INSTALL_DIR=/lore/seol/mpich3-gcc4.9.2-install
cmake .. \
  -DCMAKE_C_COMPILER="/usr/local/mpich3/latest/bin/mpicc" \
  -DCMAKE_CXX_COMPILER="/usr/local/mpich3/latest/bin/mpicxx" \
  -DCMAKE_C_FLAGS=" -g -O0 -DDEBUG -Wall -Wextra -Werror" \
  -DCMAKE_CXX_FLAGS=" -g -O0 -DDEBUG -Wall -Wextra -Werror" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_INSTALL_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_INSTALL_DIR/lib/libzoltan.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libmetis.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libparmetis.a" \
  -DENABLE_SIMMETRIX=OFF \
  -DSIM_MPI=mpich3 \
  -DSIM_DISCRETE=ON \
  -DSIMMETRIX_INCLUDE_DIR=/net/common/meshSim/$SIM_VER/include \
  -DSIMMETRIX_LIB_DIR=/net/common/meshSim/$SIM_VER/lib/$SIM_ARCHOS \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DSCOREC_CXX_WARNINGS=ON \
  -DSCOREC_CXX_OPTIMIZE=OFF \
  -DUSE_XSDK_DEFAULTS=OFF \
  -DSCOREC_ENABLE_CXX11=ON \
  -DBUILD_EXES=OFF \
  -DIS_TESTING=OFF \
  -DMESHES=/lore/seol/meshes \
  -DMPIRUN=/usr/local/mpich3/latest/bin/mpirun \
  -DCMAKE_BUILD_TYPE=Debug
