SET(LIB_REQUIRED_DEP_PACKAGES SCORECCoreapf Shards)
SET(LIB_OPTIONAL_DEP_PACKAGES
  STKIO STKMesh STKTopology STKUtil SEACASIoss)
SET(TEST_REQUIRED_DEP_PACKAGES SCORECCoreapf Shards)
SET(TEST_OPTIONAL_DEP_PACKAGES
  STKIO STKMesh STKTopology STKUtil SEACASIoss)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
