SET(LIB_REQUIRED_DEP_PACKAGES SCORECgmi SCORECpcu)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES SCORECgmi SCORECpcu)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS SimModel)
SET(LIB_OPTIONAL_DEP_TPLS SimParasolid SimAcis)
SET(TEST_REQUIRED_DEP_TPLS SimModel)
SET(TEST_OPTIONAL_DEP_TPLS SimParasolid SimAcis)

