#include <assert.h>
#include <string.h>
#include <time.h>
#include <stdio.h>

#define PH_LINE 1024
#define MAGIC 362436

static const char* magic_name = "byteorder magic number";

void ph_write_header(FILE* f, const char* name, size_t bytes,
    int nparam, int* params)
{
  int i;
  fprintf(f,"%s : < %zu > ", name, bytes);
  for (i = 0; i < nparam; ++i)
    fprintf(f, "%d ", params[i]);
  fprintf(f, "\n");
}

static void cut_trailing_spaces(char* s)
{
  char* e = s + strlen(s);
  for (--e; e >= s; --e)
    if (*e != ' ')
      break;
  ++e;
  *e = '\0';
}

void ph_parse_header(char* header, char** name, size_t* bytes,
    int nparam, int* params)
{
  char* saveptr;
  int i;
  header = strtok_r(header, ":", &saveptr);
  *name = header;
  cut_trailing_spaces(*name);
  strtok_r(NULL, "<", &saveptr);
  header = strtok_r(NULL, ">", &saveptr);
  sscanf(header, "%zu", bytes);
  for (i = 0; i < nparam; ++i) {
    header = strtok_r(NULL, " \n", &saveptr);
    sscanf(header, "%d", &params[i]);
  }
}

void ph_seek_after_header(FILE* f, char* name)
{
  char line[PH_LINE];
  char* hname;
  size_t bytes;
  while (fgets(line, sizeof(line), f)) {
    if (line[0] == '#')
      continue;
    ph_parse_header(line, &hname, &bytes, 0, NULL);
    if (!strcmp(name, hname))
      return;
    fseek(f, bytes, SEEK_CUR);
  }
}

static void get_now_string(char s[PH_LINE])
{
  time_t now;
  struct tm now_struct;
  time(&now);
  localtime_r(&now, &now_struct);
  asctime_r(&now_struct, s);
}

static void write_magic_number(FILE* f)
{
  int why = 1;
  ph_write_header(f, magic_name, sizeof(int), 1, &why);
  /* todo: expose some PCU array byte swapping tools,
     code array read/write, use it here */
}

void ph_write_preamble(FILE* f, int nodes, int vars)
{
  char timestr[PH_LINE];
  fprintf(f, "# PHASTA Input File Version 2.0\n");
  fprintf(f, "# Byte Order Magic Number : 362436 \n");
  fprintf(f, "# Output generated by phParAdapt version: \n");
  get_now_string(timestr);
  fprintf(f, "# %s\n", timestr);
  write_magic_number(f);
  ph_write_header(f, "number of modes", 0, 1, &nodes);
  ph_write_header(f, "number of variables", 0, 1, &nodes);
}
