TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    SCORECpcu
    SCORECgmi
    SCORECgmi_sim
    SCORECapf
    SCORECapf_sim
    SCORECmds
    SCORECparma
    SCORECapf_zoltan
    SCORECma
    SCORECspr
    SCORECapf_stk
  )
