TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_OPTIONAL_PACKAGES
    SCORECgmi_sim
    SCORECapf_sim
    SCORECapf_cap
  LIB_REQUIRED_PACKAGES
    SCOREClion
    SCORECpcu
    SCORECgmi
    SCORECapf
    SCORECmds
    SCORECparma
    SCORECapf_zoltan
    SCORECma
    SCORECspr
    SCORECapf_stk
    SCORECpumi
  )
