function(xsdk_compiler_flags)
  message(STATUS "Using XSDK default compiler flags")
  if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Debug" PARENT_SCOPE)
  endif()
  if(NOT user_BUILD_SHARED_LIBS)
    set(BUILD_SHARED_LIBS "ON" PARENT_SCOPE)
  endif()
endfunction(xsdk_compiler_flags)

function(xsdk_begin_package)
  if(USE_XSDK_DEFAULTS)
    message(STATUS "Using XSDK default configuration settings")
    set(user_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})
  endif()
endfunction(xsdk_begin_package)
