SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
    apf_zoltan          ../zoltan          PT  OPTIONAL
    ma                  ../ma              PT  OPTIONAL
    apf_stk             ../stk             PT  OPTIONAL
)

SET(LIB_REQUIRED_DEP_PACKAGES SCORECCore)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES SCORECCore)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)

SET(LIB_OPTIONAL_DEP_TPLS MPI)

SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
